server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #文件上传
  servlet:
    multipart:
      enabled: true
      #      最大支持文件大小
      max-file-size: 100MB
      #      最大支持请求大小
      max-request-size: 100MB

mybatis-plus:
  type-aliases-package: com.yang67.outbreakservers/entity
  mapper-locations: classpath:com/yang67/outbreakservers/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
files:
  upload:
    path: D:/sp-pr/sp_demo/files/


